

title: CSS Advanced
email: angel_beshirov@abv.bg
description: Hi there!
description: Hi there!
destination: docs
baseurl: "/Build_Design" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: don'tHAVE
github_username:  AngelBWD


# Build settings
plugins:
  - jekyll-feed


 # exclude:
 #  - .sass-cache/
 #  - .jekyll-cache/
 #  - gemfiles/
 #  - Gemfile
 #  - Gemfile.lock
 #  - node_modules
 #  - node_modules/
 #  - vendor/bundle/
 #  - vendor/cache/
 #  - vendor/gems/
#- vendor/ruby/
